sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
before_install:
  - docker build -t anastayaa/docker-react -f Dockerfile .
script:
  - docker run anastayaa/docker-react npm run test -- --coverage
after_succes:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    docker push anastayaa/docker-react ;
    fi
