version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    restart: always
  cadvisor:
    image: google/cadvisor
    restart: always
    ports:
      - "8090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
