version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_mdules
      - .:/app
    restart: always
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_mdules
      - .:/app
    command: ["npm", "run", "test"]
  cadvisor:
    image: google/cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
